name: Repo-Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_call: # by other action

permissions: {}

jobs:
  various-tests:
    concurrency:
      group: qa-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Install dependencies 🔧
        run:  |
          sudo apt update
          sudo apt install cppcheck

      - name: Run Pre-Commit Tests 🧪
        uses: j178/prek-action@v2
